### ISSUE TITLE
springboot-Security，authentication not attempted

### ISSUE THREAD

**Issue by zhaopei0418** [527515025/springBoot#1]
按照这个项目写的，我的表里只用户，角色跟权限表里没数据，
登录后什么网址都能访问，权限没用
控制台显示如下信息：
`2017-03-05 13:03:10.567 DEBUG 13087 --- [ XNIO-2 task-22] o.z.m.s.MyFilterSecurityInterceptor      : Public object - authentication not attempted`

**Comment by 527515025** [comment]
springboot －security 的设计是权限和角色信息都基于数据库。所以角色和权限表 中应该设置初始化数据。 你可以看一下 我的这篇博客 ：http://blog.csdn.net/u012373815/article/details/54633046 可能会对你有些帮助。

**Comment by zhaopei0418** [comment]
我知道为什么了，没有在权限表里的都是放行的，不做验证

**Comment by 527515025** [comment]
嗯嗯对的
